service:
  name: backendservice
#app: your-app-name
#tenant: your-tenant-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-aws-documentation
  - serverless-reqvalidator-plugin

provider:
  name: aws
  runtime: nodejs10.x

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

  environment:
    WISHLIST_TABLE: Wishlist-${self:provider.stage}
    IMAGES_BUCKET: srvrless-wishlistimages-mk9239-${self:provider.stage}
    INDEX_NAME: wishlist_index

custom:
  documentation:
    api:
      info:
        version: v1.0.0
        title: WishList API
        description: Serverless application for maintaining Wishlist of items
    models:
      - name: WishlistRequest
        contentType: application/json
        schema: ${file(src/validationmodels/createWishlistRequest.json)}


functions:
  CreateWishlistItem:
    handler: src/lambda/http/createWishlistItem.handler
    events:
      - http:
          method: post
          path: wishlistitems
          cors: true
          reqValidatorName: RequestBodyValidator
          documentation:
            summary: Create a new Wishlist Item
            description: Create a new Wishlist Item
            requestModels: 
              'application/json': WishlistRequest
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.WISHLIST_TABLE}

resources:
  Resources:

    RequestBodyValidator:
      Type: AWS::ApiGateway::RequestValidator
      Properties:
        Name: 'request-body-validator'
        RestApiId:
          Ref: ApiGatewayRestApi
        ValidateRequestBody: true
        ValidateRequestParameters: false

    TodosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: wishlistItemId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: wishlistItemId
            KeyType: HASH
          - AttributeName: userId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.WISHLIST_TABLE}
        GlobalSecondaryIndexes:
          - IndexName: ${self:provider.environment.INDEX_NAME}
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL # What attributes will be copied to an index
